### ISSUE TITLE
Error hangout on a git repo with no remote

### ISSUE THREAD

**Issue by Tornado-Tim** [odojs/enhance#2]
Error from enhance:
/usr/lib/node_modules/enhance/bin/lib.js:94
      throw err;
            ^
Error: Command failed: fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

**Comment by tcoats** [comment]
[gr](https://github.com/mixu/gr) seems like a better foundation - I'd recommend moving to gr instead.
